### ISSUE TITLE
list index out of range問題

### ISSUE THREAD

**Issue by KuKuKai** [jwlin/py-scraping-analysis-book#1]
如題，在twse_db.py中出現以下問題
in get_date_range_from_db
    date_from = datetime.datetime.strptime(list(c)[0][1], '%Y-%m-%d')

IndexError: list index out of range
請問該如何解決? 希望能順便解釋這段程式碼
![problem](https://user-images.githubusercontent.com/13616884/48270978-3fa74200-e476-11e8-99aa-ea544f816063.PNG)

**Comment by jwlin** [comment]
您好，我這邊執行範例程式沒有問題，您有把 data.sqlite3 放到與程式碼相同目錄下嗎?
變數 c[0][1] 指的是資料庫查詢結果的第一筆資料 (index 為 0) 的第二個欄位 (index 為 1)
該錯誤訊息指的是無法索引 c 中的資料，有可能是因為資料庫查詢沒有回傳東西使得變數 c 為空值。

`get_date_range_from_db()` 程式碼中，前兩行與倒數第二行是資料庫連接使用，第三行
`c.execute('select * from daily_price order by 日期 ASC LIMIT 1;')`
指的是我要從 daily_price 表中選取所有欄位，但結果依照日期由小到大排序 (ASC)，並且只要給我第一筆結果就好 (LIMIT 1)；

`datetime.strptime()` 的輸入是一個日期字串與其格式，輸出是一個 datetime 物件，字串格式可參考這裡
 https://docs.python.org/3.6/library/datetime.html#strftime-and-strptime-behavior

下圖是 daily_price 資料表定義
![db-1](https://user-images.githubusercontent.com/5249835/48667144-cd8db900-ea84-11e8-9f9b-2700e70bbcec.jpg)

資料表內容
![db-2](https://user-images.githubusercontent.com/5249835/48667146-cebee600-ea84-11e8-80cd-81fe81328e33.jpg)

**Comment by KuKuKai** [comment]
了解，由於我的資料表內容是空的所以執行程式才會出現上面的錯誤內容吧我想。
再來我想問的是下圖出現的錯誤，照上方的說明，我輸入的是一個日期字串與其格式，輸出的應該是一個 datetime 物件，可是程式卻要求字串格式而不是日期格式，這該如何解決。
![image](https://user-images.githubusercontent.com/13616884/48699564-b5ed3680-ec24-11e8-84cb-12f20b266322.png)

**Comment by jwlin** [comment]
錯誤訊息是說 `strptime()` 的第一個引數應該要是字串而非 `datetime.date` 物件。
如果你已經有了 `datetime.date` 物件，就直接使用就好，不需要轉換了吧

**Comment by KuKuKai** [comment]
了解，資料庫裡面看不出來，SELECT *出來才發現有宣告datetime.date了，十分感謝。由於我是用MySQL資料庫來做這程式，所以經常會出現關於資料庫語法的問題，十分抱歉。
