### ISSUE TITLE
scarping analysis book-finance

### ISSUE THREAD

**Issue by 499141312** [jwlin/py-scraping-analysis-book#2]
Hi JWLin,

I bought your book to learn web scraping, and tried to implement stock scraping.
But either the code in book or code on github, all got some problem shows as picture.
I've created 1 database, but it still shows this error
Could you advise which part i did wrong?
![スクリーンショット 2019-06-17 21 00 40](https://user-images.githubusercontent.com/51918387/59610896-85cb2f00-9144-11e9-97a5-7380acdabcd6.png)

**Comment by jwlin** [comment]
如果搭配範例資料庫檔案，應該能成功執行。範例資料庫在
https://github.com/jwlin/py-scraping-analysis-book/blob/master/ch8/finanance/data.sqlite3

若是自己新建資料庫，錯誤訊息是說資料庫檔案裡面沒有 daily_price 這張資料表，你有建立資料表了嗎？有建立的話，用 sqlite browser 觀察可以看到以下的資料

![image](https://user-images.githubusercontent.com/5249835/59634831-847a1200-9104-11e9-8cd8-59b2697910ed.png)

**Comment by 499141312** [comment]
感謝您的回覆, 
有試著下載範例的數據庫了, 好像是因為沒有上傳到jupyter上面才找不到。
問題已解決, 感謝您
