### ISSUE TITLE
ch7/thrsc.py

### ISSUE THREAD

**Issue by rujunz** [jwlin/py-scraping-analysis-book#3]
作者您好，因台灣高鐵時刻查詢頁面有更新，有試著跟著修改code，但無法output正確的結果，想請教code可以如何修正，謝謝您。

![高鐵時刻](https://user-images.githubusercontent.com/38936304/60523462-56f4b180-9d1d-11e9-9c4e-a6d8bf9ca0bb.png)

**Comment by jwlin** [comment]
因高鐵網頁查詢機制改變, 原程式碼已不適用; 該網頁新的機制會送出 POST 請求到另一個網址, 並回傳 JSON 檔案, 包含當日所有車次資料. 請參考新的 get_times() 函式. https://github.com/jwlin/py-scraping-analysis-book/commit/cd450dec51e5dea531f3ba315eaf8eff456f5f5a
