### ISSUE TITLE
ch8/twse_db抓取資料問題

### ISSUE THREAD

**Issue by monsters01** [jwlin/py-scraping-analysis-book#4]
您好

想請教一下，我在7/18以前執行twse_db.py是可以正常更新股價資訊到資料庫中，但在7/19再執行的時候就會報圖片上的錯誤，看起來是資料來源只剩五個值，是證交所抓取資料的方式改變了嗎? 我該如何調整呢? 謝謝您。

![圖片](https://user-images.githubusercontent.com/53483868/62138580-6e25bf80-b31a-11e9-8716-49a56bc70323.png)

**Comment by amanotaiga** [comment]
你好:
我也是這本書的讀者，我把程式從data['data5']改成data['data9']，就可以抓到資料了。
data5裡面的確只有5個值

> "data5":[["臺灣生技報酬指數","5,754.33","<p style ='color:green'>-<\u002fp>","42.38","-0.73"],

，data9的資料長得像這樣

> "data9":[["0050","元大台灣50","4,994,238","2,728","403,588,078","81.10","81.20","80.60","80.60","<p style= color:green>-<\u002fp>","1.35","80.55","55","80.60","29","0.00"]

**Comment by monsters01** [comment]
> 
> 
> 你好:
> 我也是這本書的讀者，我把程式從data['data5']改成data['data9']，就可以抓到資料了。
> data5裡面的確只有5個值
> 
> > "data5":[["臺灣生技報酬指數","5,754.33","-<\u002fp>","42.38","-0.73"],
> 
> ，data9的資料長得像這樣
> 
> > "data9":[["0050","元大台灣50","4,994,238","2,728","403,588,078","81.10","81.20","80.60","80.60","-<\u002fp>","1.35","80.55","55","80.60","29","0.00"]

您好~
我剛修改後可以正常抓到資料了，謝謝您幫我解決了疑問。
謝謝!!
